---
- name: Test hello module
  hosts: localhost
  gather_facts: false

  tasks:
    - name: run hello module
      hello:
        name: 'redhat'
      register: result

    - name: dump result
      debug:
        msg: '{{ result }}'
